### ISSUE TITLE
Errors trying to run 'python pyqt5_check.py'

### ISSUE THREAD

**Issue by KrisJanssen** [cadnano/cadnano2.5#42]
Being no python expert I naively tried to install the official python binaries on OSX El Capitan, which worked.

I then proceeded to try and run:

`python pyqt5_check.py`

Unfortunately, checker() fails:

`AttributeError: 'module' object has no attribute 'sysconfig'`

I obviously have no idea why, the error message is rather cryptic.

The line that fails seems to be:

`pyroot_path = distutils.sysconfig.BASE_PREFIX`

Unsure if this a bug or an issue on my end.

**Comment by grinner** [comment]
This is related to this [issue](https://bitbucket.org/dhellmann/virtualenvwrapper/issues/167/virtualenvwrapper_get_site_packages_dir-is), and since I never run outside a virtualenv I never saw this before. Fix coming

**Comment by KrisJanssen** [comment]
Ah, that explains things. Thanks for the heads up

**Comment by grinner** [comment]
FYI building PyQt5 from scratch is by no means simple, but in general the script I wrote should get you off the ground. Feel free to try to bump the SIP, Qt and PyQt5 versions to the latest in this file, but the PyQt configure.py file was unstable when I wrote this.  I haven't checked in a while if there is an easier solution out there since this version of cadnano is for development at the moment.

**Comment by KrisJanssen** [comment]
No worries. It seems that wget (or better the lack of it on my El Capitan system with Xcode 7) is giving me some issues as well... I'll continue fiddling about until a come across a working solution eventually. I'm also trying the Anaconda route but no luck there yet... :)

**Comment by grinner** [comment]
I fixed pyqt5_check.py for OS X in a virtualenv, might be worth trying now if you want.   Since I hadn't run it in awhile there were several things that needed tending to.  see c9202ea in the dev branch

**Comment by grinner** [comment]
Reportedly works in El Capitan now as of bc39950 .
