### ISSUE TITLE
Bump version number?

### ISSUE THREAD

**Issue by scholer** [cadnano/cadnano2.5#78]
Lots of impressive changes and commits these days! The many big changes got me thinking that maybe we should prepare for these changes (which I assume will make their way to master branch eventually!) 
When a library introduces breaking changes, this is typically indicated by incrementing the major version number. The recent changes in dnapart (and even new-pxi) seem to qualify for this. Is that something we should prepare for? Specifically, the following two questions:
1. What major version number to use? 3.0 would be natural, but maybe Nick feels this has already been used for the web/javascript-based cadnano (or the cadnano3c C++ port)? So maybe we should just bump all the way to 4.0?
2. Should we save/release a stable 2.5 version? And perhaps try to backport some of the bug-fixes from dev, new-pxi and dnapart to this? Specifically I'm thinking just renaming current master (or dev) branch to "v2.5-stable" - or create a new 2.5-stable branch branching off there. We already have some code for making scripted origami designs which uses the 2.5 cadnano library API, so it would be nice to have a persistent 2.5 version that we can use for these scripts. (And direct other people to if they wish to use our scripts as well).

**Comment by grinner** [comment]
If the master/dev branch you're using is stable we should mark it as such, and smooth out rough edges.  I'd hate to break code.  The new version in `dnapart` is almost done and drastically rethinks a lot of things, although it loads cadnano2 json files just fine.  

I'm inclined to play a wait and see game in the coming 2 weeks to see if we can't fix your code to the new API (which in all honesty isn't too different) and introduce legacy API features to keep your code running on the latest version rather than fragment the user base.  The new version will be worth the effort.

**Comment by scholer** [comment]
Nick,
Sounds nice with the new dnapart branch. Don't worry about my code, I'll just do a checkout-by-hash of the version I need until I've migrated my code to the new paradigm. I was more thinking of other potential users and software versioning best practices. But I guess since there haven't been any official "2.5" release, we don't really have to comply with that.
