### ISSUE TITLE
Binaries for an easy installation ?

### ISSUE THREAD

**Issue by hadim** [cadnano/cadnano2.5#83]
Hi guys,

I was wondering if you have binaries you could distribute for cadnano 2.5 ? I saw some pyqtdeploy code that's why I am asking...

If you don't have anything maybe I can help making scripts to generate binaries easily. Tell me what do you think.

Also which branch should I focus on ? master or dnapart from scholer ?

**Comment by sdouglas** [comment]
We're working on `pip install cadnano` that will handle everything without the need for binaries.
Once it works we'll merge with master and update the readme, hopefully in the next couple weeks.

**Comment by hadim** [comment]
`pip install cadnano` would be great indeed. But I was thinking at something more "user friendly" without the need of installing anaconda, pyqt5, etc.

However I know how hard is to do Python packaging stuff...

**Comment by sdouglas** [comment]
Experience shows releasing binaries just puts us on the hook for a lot of tedious future work to track down why everything will break with the next OS or dependency update. After 7+ years, I now just direct novice users to http://cadnano.org/legacy, which is what most labs in the field still use, due to some early stability issues with cadnano2.

Anyway, for 2.5 we're planning to have pip also fetch an appropriate version of pyqt5, so from the user perspective it'll still be a single command. We'll also get the benefit of easy updates using `pip install --update cadnano`. Anaconda won't be a dependency. If installing python and running a pip command from the terminal is too much for a user to handle, then they're also unlikely to get much marginal benefit from upgrading beyond the legacy version, at least until we add a 3D view.

**Comment by hadim** [comment]
Ok I understand your point. Thank you.
